<?php
/**
 * FILE GENERATED BY MCFACTORY - All changes made on this file will be erased when the module is republished.
 * {{$smarty.now|date_format:"%Y-%m-%d %H:%M:%S"}}
 * Copyright Jean-Christophe Cuvelier 2014
 */

require_once('lib' . DIRECTORY_SEPARATOR . 'class.{{$module->getModuleName()}}Base.php');

class {{$module->getModuleName()}} extends {{$module->getModuleName()}}Base {

    {{$module->getModuleClassLogic()|replace:'<?php':''}}

}